access:
  nether: true
  end: true
messages:
  no_access: "Zugriff auf diese Dimension ist derzeit eingeschr√§nkt."
  access_enabled: "Zugriff auf die Dimension wurde aktiviert."
  access_disabled: "Zugriff auf die Dimension wurde deaktiviert."